/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tournee` | `/tournee`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/livraisons` | `/livraisons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tournees` | `/tournees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/livraisons/[id]` | `/livraisons/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/tournees/[id]` | `/tournees/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/tournee` | `/tournee`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/livraisons` | `/livraisons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/tournees` | `/tournees`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/livraisons/[id]` | `/livraisons/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/tournees/[id]` | `/tournees/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/tournee${`?${string}` | `#${string}` | ''}` | `/tournee${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/livraisons${`?${string}` | `#${string}` | ''}` | `/livraisons${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/tournees${`?${string}` | `#${string}` | ''}` | `/tournees${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tournee` | `/tournee`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/livraisons` | `/livraisons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tournees` | `/tournees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `${'/(app)'}/livraisons/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/livraisons/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/tournees/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tournees/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/livraisons/[id]` | `/livraisons/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/tournees/[id]` | `/tournees/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
