-- Migration: Disable RLS on ALL tables
-- Description: Remove RLS restrictions, permissions managed at application level

-- Tables principales
ALTER TABLE IF EXISTS articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS articles_vendus DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cash_register DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS company_settings DISABLE ROW LEVEL SECURITY;

-- Commandes et livraisons
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_items DISABLE ROW LEVEL SECURITY;

-- Tournées et retours
ALTER TABLE IF EXISTS delivery_rounds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_round_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_return_items DISABLE ROW LEVEL SECURITY;

-- Ventes
ALTER TABLE IF EXISTS sales DISABLE ROW LEVEL SECURITY;

-- Devis client
ALTER TABLE IF EXISTS client_quote_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_quote_request_items DISABLE ROW LEVEL SECURITY;

-- Devis fournisseur
ALTER TABLE IF EXISTS supplier_quote_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_quote_request_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_quote_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_quote_response_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_quote_items DISABLE ROW LEVEL SECURITY;

-- Achats et fournisseurs
ALTER TABLE IF EXISTS suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS receptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reception_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reception_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supply_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supply_stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supply_stock_movements DISABLE ROW LEVEL SECURITY;

-- Facturation et paiements
ALTER TABLE IF EXISTS invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS invoice_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS factures DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;

-- Stock
ALTER TABLE IF EXISTS stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lots DISABLE ROW LEVEL SECURITY;

-- Configuration et autres
ALTER TABLE IF EXISTS packagings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS emballages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS packs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS document_sequences DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS fiches_trajet DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS modules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS role_permissions DISABLE ROW LEVEL SECURITY;

-- Note: La table users garde RLS activé pour la sécurité des comptes
-- Les permissions sont gérées au niveau de l'application via ProtectedModule
